theme: jekyll-theme-cayman
 baseurl: ""
  url: "https://ideasman97.github.io"
  theme_settings:
    header_text: Welcome to my Portfolio
    header_text_feature_image: assets/img/sample3.png
    footer_text: Copyright 2018